export const GET_WEATHER_LIST_REQ = 'GET_WEATHER';
export const GET_WEATHER_LIST_SUCCESS = 'GET_WEATHER_LIST_SUCCESS';
export const GET_WEATHER_LIST_FAILED = 'GET_WEATHER_LIST_FAILED';

export const GET_WEATHER_FORECAST_REQ = 'GET_WEATHER_FORECAST';
export const GET_WEATHER_FORECAST_SUCCESS = 'GET_WEATHER_FORECAST_SUCCESS';
export const GET_WEATHER_FORECAST_FAILED = 'GET_WEATHER_FORECAST_FAILED';

export const GET_WEATHER_HISTORY_REQ = 'GET_WEATHER_HISTORY';
export const GET_WEATHER_HISTORY_SUCCESS = 'GET_WEATHER_HISTORY_SUCCESS';
export const GET_WEATHER_HISTORY_FAILED = 'GET_WEATHER_HISTORY_FAILED';

export const GET_WEATHER_CITY_REQ = 'GET_WEATHER_CITY';
export const GET_WEATHER_CITY_SUCCESS = 'GET_WEATHER_CITY_SUCCESS';
export const GET_WEATHER_CITY_FAILED = 'GET_WEATHER_CITY_FAILED';
export const GET_WEATHER_CITY_RESET = 'GET_WEATHER_CITY_RESET';

export const RESET_WEATHER_DETAIL_PAGE = 'RESET_WEATHER_DETAIL_PAGE';
